name: Playwright Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test_setup:
    name: Test setup
    runs-on: ubuntu-latest
    outputs:
      preview_url: ${{ steps.waitForVercelPreviewDeployment.outputs.url }}
    steps:
      - name: Wait for Vercel preview deployment to be ready
        uses: patrickedqvist/wait-for-vercel-preview@v1.3.1
        id: waitForVercelPreviewDeployment
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          max_timeout: 600
          environment: Preview – gattner-name-corporate
      - run: echo ${{ steps.waitForVercelPreviewDeployment.outputs.url }}
  test_e2e:
    needs: test_setup
    name: Playwright tests
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install pnpm
      run: npm install -g pnpm
    - name: Install dependencies
      run: pnpm install
    - name: Build packages
      run: pnpm build:packages
      env:
        GITLAB_API_BEARER_TOKEN: ${{ secrets.GITLAB_API_BEARER_TOKEN }}
        GITLAB_PROJECT_ID: ${{ secrets.GITLAB_PROJECT_ID }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
    - name: Install corporate dependencies
      run: cd apps/corporate && pnpm install
      env:
        GITLAB_API_BEARER_TOKEN: ${{ secrets.GITLAB_API_BEARER_TOKEN }}
        GITLAB_PROJECT_ID: ${{ secrets.GITLAB_PROJECT_ID }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
    - name: Update corporate data
      run: cd apps/corporate && pnpm data:update
      env:
        GITLAB_API_BEARER_TOKEN: ${{ secrets.GITLAB_API_BEARER_TOKEN }}
        GITLAB_PROJECT_ID: ${{ secrets.GITLAB_PROJECT_ID }}
    - name: Install Playwright Browsers
      run: pnpm exec playwright install --with-deps
    - name: Run Playwright tests
      run: cd apps/corporate && pnpm test:e2e
      env:
        E2E_TEST_BASE_URL: ${{ needs.test_setup.outputs.preview_url }}
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
